version: '3.1'

services:

    mongo:
        image: mongo
        restart: 'no'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: test_root
            MONGO_INITDB_ROOT_PASSWORD: test_secret
